CRITICAL - 2024-04-16 11:24:48 --> Error: Undefined constant "Config\ENVIROMENT"
in SYSTEMPATH\Database\Config.php on line 94.
 1 SYSTEMPATH\Debug\Toolbar\Collectors\Database.php(256): CodeIgniter\Database\Config::getConnections()
 2 SYSTEMPATH\Debug\Toolbar\Collectors\Database.php(73): CodeIgniter\Debug\Toolbar\Collectors\Database->getConnections()
 3 SYSTEMPATH\Debug\Toolbar.php(65): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
 4 SYSTEMPATH\Config\Services.php(779): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
 5 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
 6 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('toolbar', [...])
 7 SYSTEMPATH\Config\Services.php(774): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', null)
 8 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::toolbar()
 9 APPPATH\Config\Events.php(47): CodeIgniter\Config\BaseService::__callStatic('toolbar', [])
10 SYSTEMPATH\Events\Events.php(154): CodeIgniter\Events\Events::Config\{closure}()
11 SYSTEMPATH\CodeIgniter.php(442): CodeIgniter\Events\Events::trigger('pre_system')
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 11:25:08 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'webloc' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('p:localhost', 'root', Object(SensitiveParameterValue), 'webloc', 3308, '', 0)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'webloc' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#5 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-16 11:25:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'webloc'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 3 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 11:25:55 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'banco' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('p:localhost', 'root', Object(SensitiveParameterValue), 'banco', 3308, '', 0)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'banco' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#5 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-16 11:25:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'banco'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 3 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 11:26:42 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'webloc' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('p:localhost', 'root', Object(SensitiveParameterValue), 'webloc', 3308, '', 0)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#2 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'webloc' in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(true)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#5 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-04-16 11:26:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'webloc'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 3 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-04-16 11:27:44 --> mysqli_sql_exception: Table 'webloc.usuario' doesn't exist in C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\tfg\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\tfg\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\tfg\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\tfg\app\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\tfg\app\Controllers\Login.php(42): App\Models\Usuario->login(Array)
#6 C:\xampp\htdocs\tfg\system\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
#7 C:\xampp\htdocs\tfg\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\tfg\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\tfg\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-04-16 11:27:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'webloc.usuario' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 2 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 3 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 11:27:44 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'webloc.usuario' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuario`')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuario`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 4 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 5 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-04-16 11:27:44 --> [Caused by] mysqli_sql_exception: Table 'webloc.usuario' doesn't exist
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *
FROM `usuario`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `usuario`')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `usuario`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`', [], false)
 5 APPPATH\Models\Usuario.php(12): CodeIgniter\Database\BaseBuilder->get()
 6 APPPATH\Controllers\Login.php(42): App\Models\Usuario->login([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->iniciarSesion()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
